AllCops:
  Exclude:
    - vendor/**/*

AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 30
#
# we like our neatly-aligned code too much
#
SingleSpaceBeforeFirstArg:
  Enabled: false
